name: Quick Build

# 快速构建工作流 - 用于测试和开发
on:
  workflow_dispatch:
    inputs:
      platform:
        description: '选择构建平台'
        required: true
        default: 'ubuntu-20.04'
        type: choice
        options:
          - ubuntu-20.04
          - macos-latest
          - windows-latest

jobs:
  quick-build:
    runs-on: ${{ github.event.inputs.platform }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          # macOS 通常不需要额外的系统依赖
          echo "macOS dependencies ready"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        run: npm run tauri build

      - name: List build outputs
        run: |
          echo "=== Build outputs ==="
          find src-tauri/target -name "*.dmg" -o -name "*.app" -o -name "*.AppImage" -o -name "*.deb" -o -name "*.rpm" -o -name "*.msi" -o -name "*.exe" 2>/dev/null || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openstore-${{ runner.os }}-${{ github.sha }}
          path: |
            src-tauri/target/release/bundle/
          retention-days: 7